=== pseyfertinsecurelogin/LHCb/Ex/DetCondExample/XMLDDDB/DTD/geometry.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Id: geometry.dtd,v 1.1 2001-12-17 15:46:13 andreav Exp $ -->

<!--XML root element, Gaudi transient root as well-->
<!ELEMENT DDDB (parameter|catalog|catalogref|logvol|surface|tabproperty)+>
<!ATTLIST DDDB version CDATA "3.3" >

<!-- include DTD for tags "tabproperty" and "tabpropertyref" -->
<!ENTITY % dtdForTabproperty SYSTEM "tabproperty.dtd" >
%dtdForTabproperty;

<!-- include DTD for tags "surface" and "surafceref" -->
<!ENTITY % dtdForSurface SYSTEM "surface.dtd" >
%dtdForSurface;

<!-- Some entities usefull for the rest of the definitions -->
<!ENTITY % solid "(box | cons | polycone | sphere | tubs | trd | trap | union | subtraction | intersection)">
<!ENTITY % simpleTransformation "((posXYZ | posRPhiZ | posRThPhi), (rotXYZ | rotAxis)?)">
<!ENTITY % transformation "(%simpleTransformation; | transformation)">
<!ENTITY % booleanchildren "((%solid;, %transformation;?), (%solid;, %transformation;?)+)">
<!ENTITY % paramphysvol "(paramphysvol | paramphysvol2D | paramphysvol3D)">


<!-- This describe a generic transformation as composition of transformations -->
<!ELEMENT transformation (%transformation;, (%transformation;)+)>

<!-- Logical volume definition
Contains 0 or 1 solid definition (shape) with a possible transformation to be
applied on it and any number (including 0) of references to its children
(physical volumes and surfaces)
Attributes:
name     - logical volume name
material - material name
-->
<!ELEMENT logvol ((%solid;, (%transformation;)?)?, (physvol | %paramphysvol; | surf)*)>
<!ATTLIST logvol
 name      ID    #REQUIRED
 material  CDATA #IMPLIED
 sensdet   CDATA #IMPLIED
 magfield  CDATA #IMPLIED
>

<!-- reference on a logical volume -->
<!ELEMENT logvolref EMPTY>
<!ATTLIST logvolref
  href CDATA #REQUIRED>

<!-- Physical volume definition.
May contain a transformation that places the logical volume given as attribute inside it
Attributes :
name   - physical volume name
logvol - a logical volume given via its name in the transient data store
-->
<!ELEMENT physvol (%transformation;)?>
<!ATTLIST physvol
  name ID #REQUIRED
  logvol CDATA #REQUIRED>

<!-- A reference to a physical volume -->
<!ELEMENT physvolref EMPTY>
<!ATTLIST physvolref
  href CDATA #REQUIRED>

<!--catalog: helps to define a partition of XML dB for domain specific part and flat store,-->
<!--         e.g. a palette of detector geometric volumes-->
<!ELEMENT catalog (catalog|catalogref|tabproperty|tabpropertyref|surface|surfaceref|logvol|logvolref)*>
<!-- <!ELEMENT catalog ANY>-->
<!--catalog: name -->
<!ATTLIST catalog
        name ID #REQUIRED>

<!--catalogref: refer to the location where the actual catalog data reside-->
<!ELEMENT catalogref EMPTY>
<!--catalogref: name -->
<!--     href : the actual URI of the catalog location-->
<!--            the form of URI is either to refer outside(1) or inside(2) a file-->
<!--            1) href="protocol://HOSTNAME/path/to/file.xml#catalogID"-->
<!--            2) href="#catalogID"-->
<!ATTLIST catalogref
        href CDATA #REQUIRED>

<!-- Parametrized physical volume definitions
This allow to copy n times a given physical volume (or a set of them
defined by another parametrised physical volume) by applying each time
a given transformation. Note that the transformation is applied in two
steps. First the volume is rotated and then translated. This means
that the volumes will be disposed on a grid.
-->

<!-- Parametrized physical volume 1D definition
Attribute :
number - the number of copies to create
-->
<!ELEMENT paramphysvol ((physvol | %paramphysvol;), %transformation;)>
<!ATTLIST paramphysvol number CDATA #REQUIRED>

<!-- Parametrized physical volume 2D definition
Attribute :
number1 - the number of copies to create for the first dimension
number2 - the number of copies to create for the second dimension
-->
<!ELEMENT paramphysvol2D ((physvol | %paramphysvol;), %transformation;, %transformation;)>
<!ATTLIST paramphysvol2D number1 CDATA #REQUIRED number2 CDATA #REQUIRED>

<!-- Parametrized physical volume 3D definition
Attribute :
number1 - the number of copies to create for the first dimension
number2 - the number of copies to create for the second dimension
number3 - the number of copies to create for the third dimension
-->
<!ELEMENT paramphysvol3D ((physvol | %paramphysvol;), %transformation;, %transformation;, %transformation;)>
<!ATTLIST paramphysvol3D number1 CDATA #REQUIRED number2 CDATA #REQUIRED number3 CDATA #REQUIRED>

<!-- Parameter definition.
A parameter is a known constant that can be used in any other expression
of the file where it is defined as well as in files referenced by this one and recursively.
As an example, your can define detector_length with value 15.4*m and use it in the
subdetector definition as in x="detector_length/10"
-->
<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
  name CDATA #REQUIRED
  value CDATA #REQUIRED>


<!-- The end of this file describes the geometry itself.
Comments are fewer but most of the definitions are obvious.
-->


<!-- Some transformations : translations and rotations in
several coordonnate systems
-->
<!ELEMENT posXYZ EMPTY>
<!ATTLIST posXYZ
  x CDATA #IMPLIED
  y CDATA #IMPLIED
  z CDATA #IMPLIED
>

<!ELEMENT posRPhiZ EMPTY>
<!ATTLIST posRPhiZ
  r   CDATA #IMPLIED
  phi CDATA #IMPLIED
  z   CDATA #IMPLIED
>

<!ELEMENT posRThPhi EMPTY>
<!ATTLIST posRThPhi
  r     CDATA #IMPLIED
  theta CDATA #IMPLIED
  phi   CDATA #IMPLIED
>

<!ELEMENT rotXYZ EMPTY>
<!ATTLIST rotXYZ
  rotX CDATA #IMPLIED
  rotY CDATA #IMPLIED
  rotZ CDATA #IMPLIED
>

<!ELEMENT rotAxis EMPTY>
<!ATTLIST rotAxis
  axTheta CDATA #IMPLIED
  axPhi CDATA #IMPLIED
  angle CDATA #IMPLIED
>


<!-- CSG solids.
box is obvious.
trd is a simple trapezoid defined by two rectangles orthogonal
    to the z axis and centered on it and a Z size.
trap is a more generic trapezoid defined by a direction (theta, phi)
    that replaces the previous Z axis, a length along this axe (sizeZ)
    and two faces which are kinds of trapezes. Actually, they are
    defined by two parallel segments of length X?, the distance between
    the two (Y?) and the angle between the orthogonal line to these
    segments and the line joining the middle of both segments (alp?)
tubs is a part of a section of tub. The tub is centered on the z axis
    and defined by its inner and outer radius. It is then cut to keep
    a section of length sizeZ centered at the origin. At last, only
    the part between phi = startPhiAngle and phi = startPhiAngle +
    deltaPhiAngle is kept.
cons is a part of a section of cone. The cone is defined along Z and its
    section is defined by the inner and outer radius at each extremity
    plus the height of the section. outerRadiusPZ for example gives the
    outer radius at the extremity that has a positive (the P) Z.
    At last, only the part between phi = startPhiAngle and phi =
    startPhiAngle + deltaPhiAngle is kept.
polycone is several cone sections. The cone is defined along Z and the
    sections are defined by a number of triplets giving for several
    location in z the inner and outer radiuses of the polycone in these
    places. At last, only the part between phi = startPhiAngle and phi =
    startPhiAngle + deltaPhiAngle is kept.
sphere is a kind of sphere part but with a thickness. The thick sphere is
    defined by a inner and an outer radius. Then only a portion of
    the whole sphere is kept, defined by its theta and phi angles.
-->
<!ELEMENT box EMPTY>
<!ATTLIST box
	name  ID    #REQUIRED
	sizeX CDATA #REQUIRED
	sizeY CDATA #REQUIRED
	sizeZ CDATA #REQUIRED
>
<!ELEMENT trd EMPTY>
<!ATTLIST trd
	name   ID    #REQUIRED
	sizeZ  CDATA #REQUIRED
	sizeX1 CDATA #REQUIRED
	sizeY1 CDATA #REQUIRED
	sizeX2 CDATA #REQUIRED
	sizeY2 CDATA #REQUIRED
>
<!ELEMENT trap EMPTY>
<!ATTLIST trap
	name   ID    #REQUIRED
	sizeZ  CDATA #REQUIRED
        theta  CDATA #IMPLIED
        phi    CDATA #IMPLIED
	sizeY1 CDATA #REQUIRED
	sizeX1 CDATA #REQUIRED
	sizeX2 CDATA #REQUIRED
        alp1   CDATA #IMPLIED
	sizeY2 CDATA #REQUIRED
	sizeX3 CDATA #REQUIRED
	sizeX4 CDATA #REQUIRED
        alp2   CDATA #IMPLIED
>
<!ELEMENT tubs EMPTY>
<!ATTLIST tubs
	name          ID    #REQUIRED
	sizeZ         CDATA #REQUIRED
	outerRadius   CDATA #REQUIRED
	innerRadius   CDATA #IMPLIED
	startPhiAngle CDATA #IMPLIED
	deltaPhiAngle CDATA #IMPLIED
>
<!ELEMENT cons EMPTY>
<!ATTLIST cons
	name          ID    #REQUIRED
	sizeZ         CDATA #REQUIRED
	outerRadiusPZ CDATA #REQUIRED
	outerRadiusMZ CDATA #REQUIRED
	innerRadiusPZ CDATA #IMPLIED
	innerRadiusMZ CDATA #IMPLIED
	startPhiAngle CDATA #IMPLIED
	deltaPhiAngle CDATA #IMPLIED
>
<!ELEMENT polycone (zplane, zplane+)>
<!ATTLIST polycone
	name          ID    #REQUIRED
	startPhiAngle CDATA #IMPLIED
	deltaPhiAngle CDATA #IMPLIED
>
<!ELEMENT zplane EMPTY>
<!ATTLIST zplane
	z             CDATA #REQUIRED
	outerRadius   CDATA #REQUIRED
	innerRadius   CDATA #IMPLIED
>
<!ELEMENT sphere EMPTY>
<!ATTLIST sphere
	name            ID    #REQUIRED
	outerRadius     CDATA #REQUIRED
	innerRadius     CDATA #IMPLIED
	startPhiAngle   CDATA #IMPLIED
	deltaPhiAngle   CDATA #IMPLIED
	startThetaAngle CDATA #IMPLIED
	deltaThetaAngle CDATA #IMPLIED
>

<!-- Boolean solids
The way these boolean solids are processed is that the children
are processed one by one, the transformation following it (if there
is one is applied) and finally the boolean operation is applied
between the preceeding result and the new processed child.
-->
<!ELEMENT union (%booleanchildren;)>
<!ATTLIST union name ID #REQUIRED>

<!ELEMENT subtraction (%booleanchildren;)>
<!ATTLIST subtraction name ID #REQUIRED>

<!ELEMENT intersection (%booleanchildren;)>
<!ATTLIST intersection name ID #REQUIRED>

=== pseyfertinsecurelogin/LHCb/Ex/DetCondExample/XMLDDDB/Ecal/Installation/Mid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DDDB SYSTEM "../../DTD/geometry.dtd">
<DDDB>
<!-- """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" --> 
<!--   
  CVS tag: $Name: not supported by cvs2svn $
  $Log: not supported by cvs2svn $
  Revision 1.1.1.1  2007/01/30 13:34:59  marcocle
  CVS based back up for the SQLite conditions database

  Revision 1.6  2006/02/06 15:54:00  cattanem
  DC06 geometry and cleanup of older stuff

  Revision 1.5  2005/06/06 15:59:43  gcorti
  Calo tilt

  Revision 1.4  2003/12/05 13:59:43  cattanem
  add Calo changes

  Revision 1.3  2002/09/12 09:32:57  cattanem
  Add vertical Rich, Velo optimisation

  Revision 1.2  2002/02/28 10:28:59  pakhlova
  *** empty log message ***

  Revision 1.1  2001/12/15 16:05:36  ibelyaev
  The first version of  detailed Ecal description by Galina Pakhlova
--> 
<!-- """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" --> 
<!-- ******************************************************************* --> 
<!--  Geometry of the Middle Section of the Electromagnetic Calorimeter  -->
<!--                    Logical Volumes Definition                       --> 
<!-- ******************************************************************* --> 

<!-- %%% Ecal Middle Section %%% -->

  <logvol name = "MidSection" material="Vacuum">

   <subtraction name = "Ecal_Middle_Section">
         <box  name  = "Middle_Box"
                sizeX = "EcalMidXSize"
                sizeY = "EcalMidYSize"
                sizeZ = "EcalMidModLength"/>

             <box  name  = "Middle_Subtracted_Box"
                   sizeX = "EcalInnXSize"
                   sizeY = "EcalInnYSize"
                   sizeZ = "EcalMidModLength+EcalTolerance"/>
   </subtraction>

<!-- % Middle Block Installation as Matrix Elements of Middle Section % --> 
                         
  <paramphysvol2D number1 = "4" number2 = "2">
      <physvol name = "Middle_Up_Rows"
               logvol = "/dd/Geometry/DownstreamRegion/Ecal/Installation/MidBlock">
                  <posXYZ x = "-12*EcalModXSize"
                          y = " 9*EcalModYSize"/>
      </physvol>
           <posXYZ x = "8*EcalModXSize"/>
           <posXYZ y = "-2*EcalModYSize"/>
   </paramphysvol2D>

    <paramphysvol2D number1 = "2" number2 = "6">
      <physvol name = "Middle_Left_Right_Rows"
               logvol = "/dd/Geometry/DownstreamRegion/Ecal/Installation/MidBlock">
                  <posXYZ x ="-12*EcalModXSize"
                          y =" 5*EcalModYSize"/>
      </physvol>
           <posXYZ x = "24*EcalModXSize"/>
           <posXYZ y = "-2*EcalModYSize"/>
    </paramphysvol2D>

    <paramphysvol2D number1 = "4" number2 = "2">                      
       <physvol name = "Middle_Down_Rows"
                logvol = "/dd/Geometry/DownstreamRegion/Ecal/Installation/MidBlock">
                   <posXYZ x = "-12*EcalModXSize"
                           y = " -9*EcalModYSize"/>
       </physvol>
           <posXYZ x = "8*EcalModXSize"/>
           <posXYZ y = "2*EcalModYSize"/>
    </paramphysvol2D>
   </logvol>
<!-- ******************************************************************* -->

<!-- %%% Ecal Middle Block %%% -->

<logvol name = "MidBlock" material="Vacuum">
    <box  name  = "Middle_Block"
                   sizeX = "8*EcalModXSize"
                   sizeY = "2*EcalModYSize"
                   sizeZ = "EcalMidModLength"/>

<!-- %%% Ecal Module Installation as 8 x 2 Matrix Elements 
                                  of Middle Block Section %%% -->                        
   <paramphysvol2D number1 = "8" number2 = "2">
      <physvol name = "Middle_Module_Rows"
               logvol = "/dd/Geometry/DownstreamRegion/Ecal/Modules/Middle">
                  <posXYZ x = "-3.5*EcalModXSize"
                          y = " 0.5*EcalModYSize"/>
      </physvol>
           <posXYZ x = "   EcalModXSize"/>
           <posXYZ y = "-1*EcalModYSize"/>
   </paramphysvol2D>
  </logvol>
<!-- ******************************************************************* -->
 </DDDB>

=== pseyfertinsecurelogin/LHCb/Ex/DetCondExample/XMLDDDB/Ecal/Modules/InnMod.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DDDB SYSTEM "../../DTD/geometry.dtd">
<DDDB>
<!-- """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" --> 
<!--   
  CVS tag: $Name: not supported by cvs2svn $
  $Log: not supported by cvs2svn $
  Revision 1.1.1.1  2007/01/30 13:34:59  marcocle
  CVS based back up for the SQLite conditions database

  Revision 1.7  2006/02/06 15:54:00  cattanem
  DC06 geometry and cleanup of older stuff

  Revision 1.6  2005/06/06 15:59:43  gcorti
  Calo tilt

  Revision 1.5  2003/12/05 13:59:43  cattanem
  add Calo changes

  Revision 1.4  2003/06/19 06:18:22  cattanem
  v16r0

  Revision 1.3  2002/09/12 09:32:58  cattanem
  Add vertical Rich, Velo optimisation

  Revision 1.2  2002/01/19 13:58:42  ibelyaev
   fix the bug with material names/paths

  Revision 1.1  2001/12/15 16:05:37  ibelyaev
  The first version of  detailed Ecal description by Galina Pakhlova
 
--> 
<!-- """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" --> 
<!-- ******************************************************************** --> 
<!--                      Ecal Inner Module Geometry                      -->
<!--                      Logical Volumes Definition                      --> 
<!-- ******************************************************************** --> 

 <logvol name = "Inner" material = "Ecal/EcalSteel">

   <box  name  = "Inner_Module_Box"
         sizeX = "EcalModXSize"
         sizeY = "EcalModYSize"
         sizeZ = "EcalInnModLength"/>

    <physvol name = "InnerModuleFrontCover"
             logvol = "/dd/Geometry/DownstreamRegion/Ecal/Modules/InnFrontCover"> 
               <posXYZ z = "EcalInnFrontCoverOffset"/>
    </physvol>

    <physvol name   = "InnerModuleBackCover"
             logvol = "/dd/Geometry/DownstreamRegion/Ecal/Modules/InnBackCover"> 
               <posXYZ z = "EcalInnBackCoverOffset"/>
    </physvol>
 
    <physvol name = "InnerModuleReadOut"
             logvol = "/dd/Geometry/DownstreamRegion/Ecal/Modules/InnReadOut"> 
                <posXYZ  z = "EcalInnReadOutOffset"/>
    </physvol> 

   <physvol name   = "InnerModuleStack"
             logvol = "/dd/Geometry/DownstreamRegion/Ecal/Modules/InnStack"> 
                <posXYZ  z = "EcalInnStackOffset"/>
   </physvol>

  </logvol>
<!-- ***************************************************************** --> 
<!--                Ecal Inner Module Front Cover Geometry             -->
<!-- ***************************************************************** --> 
  <logvol name = "InnFrontCover" material = "Ecal/EcalPlasticInnFC">
         <box  name  = "Inner_Module_Front_Cover_Box"
               sizeX = "EcalModXSize" 
               sizeY = "EcalModYSize"
               sizeZ = "EcalInnFrontCoverLength"/>
  </logvol>
<!-- ***************************************************************** --> 
<!--                Ecal Inner Module Back Cover Geometry              -->
<!-- ***************************************************************** --> 
  <logvol name = "InnBackCover" material = "Ecal/EcalPlasticBC">
         <box  name  = "Inner_Module_Back_Cover_Box"
               sizeX = "EcalModXSize"
               sizeY = "EcalModYSize"
               sizeZ = "EcalInnBackCoverLength"/>
  </logvol>
<!-- ****************************************************************** --> 
<!--                Ecal Inner Module Read Out Geometry                 -->
<!-- ****************************************************************** --> 
  <logvol name = "InnReadOut" material = "Vacuum">
         <box  name  = "Inner_Module_Read_Out_Box"
               sizeX = "EcalModXSize"
               sizeY = "EcalModYSize"
               sizeZ = "EcalInnReadOutLength"/>
 
      <physvol name   = "InnerReadOutBox"
	       logvol = "/dd/Geometry/DownstreamRegion/Ecal/Modules/InnReadOutBox"> 
      </physvol>       
 </logvol>
<!-- ****************************************************************** --> 
<!--              Ecal Outer Module Read Out Tube                       -->
<!-- ****************************************************************** --> 
  <logvol name = "InnReadOutBox" material = "Ecal/EcalPlasticBC">
         <box  name  = "Inner_Read_Out_Box"
	       sizeX = "EcalInnReadOutX"
               sizeY = "EcalInnReadOutY"
               sizeZ = "EcalInnReadOutLength"/>
  </logvol>
<!-- ****************************************************************** --> 
<!--                Ecal Inner Module Stack Geometry                    -->
<!-- ****************************************************************** --> 
 <logvol name = "InnStack" material = "Vacuum">
         <box  name  = "Inner_Stack_Main_Box"
               sizeX = "EcalModXSize-2*EcalTapeThick"
               sizeY = "EcalModYSize-2*EcalTapeThick"
               sizeZ = "EcalStackLength"/>

<!-- %%% Inner Cells Installation as 3x3 Matrix of the Inner Module %%% -->

    <paramphysvol2D number1 = "3" number2 = "3">
      <physvol name = "Inner_Cells_Matrix"
               logvol ="/dd/Geometry/DownstreamRegion/Ecal/Modules/InnCell">
                    <posXYZ x = "-1*EcalInnCellXYSize"
                            y = "   EcalInnCellXYSize"/>
      </physvol>
           <posXYZ x = "EcalInnCellXYSize"/>
           <posXYZ y = "-1*EcalInnCellXYSize"/>
    </paramphysvol2D>
  </logvol>
<!-- ****************************************************************** --> 
</DDDB>

=== pseyfertinsecurelogin/LHCb/Ex/DetCondExample/XMLDDDB/Ecal/Modules/InnCellPlates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DDDB SYSTEM "../../DTD/geometry.dtd">
<DDDB>
  <!-- """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" --> 
  <!--   
  CVS tag: $Name: not supported by cvs2svn $
  $Log: not supported by cvs2svn $
  Revision 1.1.1.1  2007/01/30 13:34:59  marcocle
  CVS based back up for the SQLite conditions database

  Revision 1.7  2006/02/06 15:54:00  cattanem
  DC06 geometry and cleanup of older stuff

  Revision 1.6  2005/06/06 15:59:43  gcorti
  Calo tilt

  Revision 1.5  2003/06/19 06:18:22  cattanem
  v16r0

  Revision 1.4  2003/02/11 13:29:20  ranjard
  v15r3 - Add some missing sensitive detector declarations for Ecal

  Revision 1.3  2002/09/12 09:32:58  cattanem
  Add vertical Rich, Velo optimisation
  
  Revision 1.2  2002/01/19 13:58:42  ibelyaev
  fix the bug with material names/paths
  
  Revision 1.1  2001/12/15 16:05:37  ibelyaev
  The first version of  detailed Ecal description by Galina Pakhlova
  
  --> 
 <!-- """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" --> 
  
 <!-- For Inner Cell:
  Plastic Plate, Steel Plate, Pb Plate
  Geometry Logical Volumes are defined                           --> 
  
<!-- ******************************************************************* --> 
<!--                 Inner Cell: Plastic Plate Geometry                  -->
<!-- ******************************************************************* --> 
  
  <logvol name = "InnCellPlastic" material = "Ecal/EcalPlastic" >
      <box   name  = "Plastic_Cell_Box"
             sizeX = "EcalInnCellXYSize"
             sizeY = "EcalInnCellXYSize"
             sizeZ = "EcalPlasticThick"/>
  </logvol>

<!-- ******************************************************************* --> 
<!--                 Inner Cell: Steel Plate Geometry                    -->
<!-- ******************************************************************* --> 
  
  <logvol name = "InnCellSteel" material = "Ecal/EcalSteel">
      <box   name  = "Steel_Cell_Box"
             sizeX = "EcalInnCellXYSize"
             sizeY = "EcalInnCellXYSize"
             sizeZ = "EcalSteelThick"/>
  </logvol>

<!-- ******************************************************************* --> 
<!--                   Inner Cell: Pb Plate Geometry                     -->
<!-- ******************************************************************* --> 
  
  <logvol name = "InnCellPb" material = "Ecal/EcalPb">
      <box   name  = "Pb_Cell_Box"
             sizeX = "EcalInnCellXYSize"
             sizeY = "EcalInnCellXYSize"
             sizeZ = "EcalPbThick"/>
    
    <!-- %%%  Fiber Installation into Pb Cell   %%% -->
    
    <paramphysvol2D number1 = "4" number2 = "4">
      <physvol name = "InnerPbFiber"
        logvol = "/dd/Geometry/DownstreamRegion/Ecal/Modules/FiberPb">
        <posXYZ x = "-1.5*EcalInnSubCellXYSize"
          y = " 1.5*EcalInnSubCellXYSize"/>
      </physvol>
            <posXYZ x = "EcalInnSubCellXYSize"/>
            <posXYZ y = "-1*EcalInnSubCellXYSize"/>
    </paramphysvol2D>
    <!-- %%%%%%%%%%% -->                                         
 
 </logvol>

<!-- ******************************************************************* -->
</DDDB>
