=== pseyfertinsecurelogin/LHCb/Ex/DetCondExample/XMLDDDB/DTD/geometry.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Id: geometry.dtd,v 1.1 2001-12-17 15:46:13 andreav Exp $ -->

<!--XML root element, Gaudi transient root as well-->
<!ELEMENT DDDB (parameter|catalog|catalogref|logvol|surface|tabproperty)+>
<!ATTLIST DDDB version CDATA "3.3" >

<!-- include DTD for tags "tabproperty" and "tabpropertyref" -->
<!ENTITY % dtdForTabproperty SYSTEM "tabproperty.dtd" >
%dtdForTabproperty;

<!-- include DTD for tags "surface" and "surafceref" -->
<!ENTITY % dtdForSurface SYSTEM "surface.dtd" >
%dtdForSurface;

<!-- Some entities usefull for the rest of the definitions -->
<!ENTITY % solid "(box | cons | polycone | sphere | tubs | trd | trap | union | subtraction | intersection)">
<!ENTITY % simpleTransformation "((posXYZ | posRPhiZ | posRThPhi), (rotXYZ | rotAxis)?)">
<!ENTITY % transformation "(%simpleTransformation; | transformation)">
<!ENTITY % booleanchildren "((%solid;, %transformation;?), (%solid;, %transformation;?)+)">
<!ENTITY % paramphysvol "(paramphysvol | paramphysvol2D | paramphysvol3D)">


<!-- This describe a generic transformation as composition of transformations -->
<!ELEMENT transformation (%transformation;, (%transformation;)+)>

<!-- Logical volume definition
Contains 0 or 1 solid definition (shape) with a possible transformation to be
applied on it and any number (including 0) of references to its children
(physical volumes and surfaces)
Attributes:
name     - logical volume name
material - material name
-->
<!ELEMENT logvol ((%solid;, (%transformation;)?)?, (physvol | %paramphysvol; | surf)*)>
<!ATTLIST logvol
 name      ID    #REQUIRED
 material  CDATA #IMPLIED
 sensdet   CDATA #IMPLIED
 magfield  CDATA #IMPLIED
>

<!-- reference on a logical volume -->
<!ELEMENT logvolref EMPTY>
<!ATTLIST logvolref
  href CDATA #REQUIRED>

<!-- Physical volume definition.
May contain a transformation that places the logical volume given as attribute inside it
Attributes :
name   - physical volume name
logvol - a logical volume given via its name in the transient data store
-->
<!ELEMENT physvol (%transformation;)?>
<!ATTLIST physvol
  name ID #REQUIRED
  logvol CDATA #REQUIRED>

<!-- A reference to a physical volume -->
<!ELEMENT physvolref EMPTY>
<!ATTLIST physvolref
  href CDATA #REQUIRED>

<!--catalog: helps to define a partition of XML dB for domain specific part and flat store,-->
<!--         e.g. a palette of detector geometric volumes-->
<!ELEMENT catalog (catalog|catalogref|tabproperty|tabpropertyref|surface|surfaceref|logvol|logvolref)*>
<!-- <!ELEMENT catalog ANY>-->
<!--catalog: name -->
<!ATTLIST catalog
        name ID #REQUIRED>

<!--catalogref: refer to the location where the actual catalog data reside-->
<!ELEMENT catalogref EMPTY>
<!--catalogref: name -->
<!--     href : the actual URI of the catalog location-->
<!--            the form of URI is either to refer outside(1) or inside(2) a file-->
<!--            1) href="protocol://HOSTNAME/path/to/file.xml#catalogID"-->
<!--            2) href="#catalogID"-->
<!ATTLIST catalogref
        href CDATA #REQUIRED>

<!-- Parametrized physical volume definitions
This allow to copy n times a given physical volume (or a set of them
defined by another parametrised physical volume) by applying each time
a given transformation. Note that the transformation is applied in two
steps. First the volume is rotated and then translated. This means
that the volumes will be disposed on a grid.
-->

<!-- Parametrized physical volume 1D definition
Attribute :
number - the number of copies to create
-->
<!ELEMENT paramphysvol ((physvol | %paramphysvol;), %transformation;)>
<!ATTLIST paramphysvol number CDATA #REQUIRED>

<!-- Parametrized physical volume 2D definition
Attribute :
number1 - the number of copies to create for the first dimension
number2 - the number of copies to create for the second dimension
-->
<!ELEMENT paramphysvol2D ((physvol | %paramphysvol;), %transformation;, %transformation;)>
<!ATTLIST paramphysvol2D number1 CDATA #REQUIRED number2 CDATA #REQUIRED>

<!-- Parametrized physical volume 3D definition
Attribute :
number1 - the number of copies to create for the first dimension
number2 - the number of copies to create for the second dimension
number3 - the number of copies to create for the third dimension
-->
<!ELEMENT paramphysvol3D ((physvol | %paramphysvol;), %transformation;, %transformation;, %transformation;)>
<!ATTLIST paramphysvol3D number1 CDATA #REQUIRED number2 CDATA #REQUIRED number3 CDATA #REQUIRED>

<!-- Parameter definition.
A parameter is a known constant that can be used in any other expression
of the file where it is defined as well as in files referenced by this one and recursively.
As an example, your can define detector_length with value 15.4*m and use it in the
subdetector definition as in x="detector_length/10"
-->
<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
  name CDATA #REQUIRED
  value CDATA #REQUIRED>


<!-- The end of this file describes the geometry itself.
Comments are fewer but most of the definitions are obvious.
-->


<!-- Some transformations : translations and rotations in
several coordonnate systems
-->
<!ELEMENT posXYZ EMPTY>
<!ATTLIST posXYZ
  x CDATA #IMPLIED
  y CDATA #IMPLIED
  z CDATA #IMPLIED
>

<!ELEMENT posRPhiZ EMPTY>
<!ATTLIST posRPhiZ
  r   CDATA #IMPLIED
  phi CDATA #IMPLIED
  z   CDATA #IMPLIED
>

<!ELEMENT posRThPhi EMPTY>
<!ATTLIST posRThPhi
  r     CDATA #IMPLIED
  theta CDATA #IMPLIED
  phi   CDATA #IMPLIED
>

<!ELEMENT rotXYZ EMPTY>
<!ATTLIST rotXYZ
  rotX CDATA #IMPLIED
  rotY CDATA #IMPLIED
  rotZ CDATA #IMPLIED
>

<!ELEMENT rotAxis EMPTY>
<!ATTLIST rotAxis
  axTheta CDATA #IMPLIED
  axPhi CDATA #IMPLIED
  angle CDATA #IMPLIED
>


<!-- CSG solids.
box is obvious.
trd is a simple trapezoid defined by two rectangles orthogonal
    to the z axis and centered on it and a Z size.
trap is a more generic trapezoid defined by a direction (theta, phi)
    that replaces the previous Z axis, a length along this axe (sizeZ)
    and two faces which are kinds of trapezes. Actually, they are
    defined by two parallel segments of length X?, the distance between
    the two (Y?) and the angle between the orthogonal line to these
    segments and the line joining the middle of both segments (alp?)
tubs is a part of a section of tub. The tub is centered on the z axis
    and defined by its inner and outer radius. It is then cut to keep
    a section of length sizeZ centered at the origin. At last, only
    the part between phi = startPhiAngle and phi = startPhiAngle +
    deltaPhiAngle is kept.
cons is a part of a section of cone. The cone is defined along Z and its
    section is defined by the inner and outer radius at each extremity
    plus the height of the section. outerRadiusPZ for example gives the
    outer radius at the extremity that has a positive (the P) Z.
    At last, only the part between phi = startPhiAngle and phi =
    startPhiAngle + deltaPhiAngle is kept.
polycone is several cone sections. The cone is defined along Z and the
    sections are defined by a number of triplets giving for several
    location in z the inner and outer radiuses of the polycone in these
    places. At last, only the part between phi = startPhiAngle and phi =
    startPhiAngle + deltaPhiAngle is kept.
sphere is a kind of sphere part but with a thickness. The thick sphere is
    defined by a inner and an outer radius. Then only a portion of
    the whole sphere is kept, defined by its theta and phi angles.
-->
<!ELEMENT box EMPTY>
<!ATTLIST box
	name  ID    #REQUIRED
	sizeX CDATA #REQUIRED
	sizeY CDATA #REQUIRED
	sizeZ CDATA #REQUIRED
>
<!ELEMENT trd EMPTY>
<!ATTLIST trd
	name   ID    #REQUIRED
	sizeZ  CDATA #REQUIRED
	sizeX1 CDATA #REQUIRED
	sizeY1 CDATA #REQUIRED
	sizeX2 CDATA #REQUIRED
	sizeY2 CDATA #REQUIRED
>
<!ELEMENT trap EMPTY>
<!ATTLIST trap
	name   ID    #REQUIRED
	sizeZ  CDATA #REQUIRED
        theta  CDATA #IMPLIED
        phi    CDATA #IMPLIED
	sizeY1 CDATA #REQUIRED
	sizeX1 CDATA #REQUIRED
	sizeX2 CDATA #REQUIRED
        alp1   CDATA #IMPLIED
	sizeY2 CDATA #REQUIRED
	sizeX3 CDATA #REQUIRED
	sizeX4 CDATA #REQUIRED
        alp2   CDATA #IMPLIED
>
<!ELEMENT tubs EMPTY>
<!ATTLIST tubs
	name          ID    #REQUIRED
	sizeZ         CDATA #REQUIRED
	outerRadius   CDATA #REQUIRED
	innerRadius   CDATA #IMPLIED
	startPhiAngle CDATA #IMPLIED
	deltaPhiAngle CDATA #IMPLIED
>
<!ELEMENT cons EMPTY>
<!ATTLIST cons
	name          ID    #REQUIRED
	sizeZ         CDATA #REQUIRED
	outerRadiusPZ CDATA #REQUIRED
	outerRadiusMZ CDATA #REQUIRED
	innerRadiusPZ CDATA #IMPLIED
	innerRadiusMZ CDATA #IMPLIED
	startPhiAngle CDATA #IMPLIED
	deltaPhiAngle CDATA #IMPLIED
>
<!ELEMENT polycone (zplane, zplane+)>
<!ATTLIST polycone
	name          ID    #REQUIRED
	startPhiAngle CDATA #IMPLIED
	deltaPhiAngle CDATA #IMPLIED
>
<!ELEMENT zplane EMPTY>
<!ATTLIST zplane
	z             CDATA #REQUIRED
	outerRadius   CDATA #REQUIRED
	innerRadius   CDATA #IMPLIED
>
<!ELEMENT sphere EMPTY>
<!ATTLIST sphere
	name            ID    #REQUIRED
	outerRadius     CDATA #REQUIRED
	innerRadius     CDATA #IMPLIED
	startPhiAngle   CDATA #IMPLIED
	deltaPhiAngle   CDATA #IMPLIED
	startThetaAngle CDATA #IMPLIED
	deltaThetaAngle CDATA #IMPLIED
>

<!-- Boolean solids
The way these boolean solids are processed is that the children
are processed one by one, the transformation following it (if there
is one is applied) and finally the boolean operation is applied
between the preceeding result and the new processed child.
-->
<!ELEMENT union (%booleanchildren;)>
<!ATTLIST union name ID #REQUIRED>

<!ELEMENT subtraction (%booleanchildren;)>
<!ATTLIST subtraction name ID #REQUIRED>

<!ELEMENT intersection (%booleanchildren;)>
<!ATTLIST intersection name ID #REQUIRED>

=== pseyfertinsecurelogin/LHCb/Det/VeloDet/tests/data/DB/simple/Velo/Geom/LogVol/Velo.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
    (c) Copyright 2018 CERN for the benefit of the LHCb Collaboration

    This software is distributed under the terms of the GNU General Public
    Licence version 3 (GPL Version 3), copied verbatim in the file "COPYING".

    In applying this licence, CERN does not waive the privileges and immunities
    granted to it by virtue of its status as an Intergovernmental Organization
    or submit itself to any jurisdiction.
-->
<!DOCTYPE DDDB SYSTEM "git:/DTD/geometry.dtd" >
<DDDB>

  <!-- Geometry for Vertex detector -->

  <logvol name="lvVelo" material="Vacuum">
      <tubs name="VeloTubs1"
            sizeZ         = "1670*mm"
            innerRadius   = "0*mm"
            outerRadius   = "590*mm"
            startPhiAngle = "0*degree"
            deltaPhiAngle = "360*degree"/>

    <physvol name="pvVeloLeft" logvol="/dd/Geometry/BeforeMagnetRegion/Velo/lvVeloLeft">
      <posXYZ x="0*mm" y="0*mm" z="0*mm"/>
    </physvol>

    <physvol name="pvVeloRight" logvol="/dd/Geometry/BeforeMagnetRegion/Velo/lvVeloRight">
      <posXYZ x="0*mm" y="0*mm" z="0*mm"/>
    </physvol>

  </logvol>

  <logvol name="lvVeloRight" material="Vacuum">
    <box name="rightmod" sizeX = "5*mm" sizeY = "5*mm" sizeZ = "5*mm" />
  </logvol>


  <logvol name="lvVeloLeft" material="Vacuum">
    <box name="leftmod" sizeX = "5*mm" sizeY = "5*mm" sizeZ = "5*mm" />
  </logvol>

</DDDB>

=== pseyfertinsecurelogin/LHCb/Ex/DetCondExample/XMLDDDB/Hcal/Cells/OuterFilling.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DDDB SYSTEM "../../DTD/geometry.dtd">
<DDDB>

<!--

   $Id: OuterFilling.xml,v 1.1 2007-02-02 18:19:30 marcocle Exp $ 
   CVS tag $Name: not supported by cvs2svn $
   $Log: not supported by cvs2svn $
   Revision 1.1.1.1  2007/01/30 13:34:59  marcocle
   CVS based back up for the SQLite conditions database

   Revision 1.7  2006/02/06 15:54:01  cattanem
   DC06 geometry and cleanup of older stuff

   Revision 1.6  2005/06/06 16:03:09  gcorti
   Calo tilt

   Revision 1.5  2003/07/10 14:56:28  cattanem
   changes for v17r0 - see release notes

   Revision 1.4  2003/05/28 13:48:17  cattanem
   changes from Sajan, Witek, Patrick

   Revision 1.3  2002/09/12 09:33:01  cattanem
   Add vertical Rich, Velo optimisation

   Revision 1.2  2002/01/19 16:20:32  aberdiou
    new description of Hcal


-->

  <!-- **************************************************************** --> 
  <!--    Geometry of the Filling (Tile, Spacers, Master Plate etc.)    -->
  <!--         in the Outer Cells of the Hadronic Calorimeter           -->
  <!-- **************************************************************** --> 
  <!--                   Logical Volumes Definition                     --> 
  <!-- **************************************************************** --> 
  <!-- %%%%%%%%%%              Master Plate                  %%%%%%%%%% -->
  <!-- **************************************************************** --> 
  <logvol name = "lvHcalOutCellMsPl" material = "Hcal/HcalMsPlSteel">
    <box name  = "HcalOutCellMsPlBox"
      sizeX = "HcalMsPlWidth"
      sizeY = "HcalMsPlHeight"
      sizeZ = "2.0*HcalMsPlStepLength"/>
    <physvol name = "pvHcalOutCell1stCalHoleMsPl"
      logvol = "/dd/Geometry/DownstreamRegion/Hcal/Cells/lvHcalOutCellCalHoleMsPl"> 
      <posXYZ x = "0.0*mm"
              y = "0.0*mm"
              z = "-0.5*HcalMsPlStepLength"/>
      <rotXYZ rotY="90*degree"/>
    </physvol>
    <physvol name = "pvHcalOutCell2ndCalHoleMsPl"
      logvol = "/dd/Geometry/DownstreamRegion/Hcal/Cells/lvHcalOutCellCalHoleMsPl"> 
      <posXYZ x = "0.0*mm"
              y = "0.0*mm"
              z = "0.5*HcalMsPlStepLength"/>
      <rotXYZ rotY="90*degree"/>
    </physvol>
  </logvol> 
  <!-- **************************************************************** --> 
  <!-- %%%%%%%%%%             Scintillating Tile             %%%%%%%%%% -->
  <!-- **************************************************************** --> 
  <logvol 
    name     = "lvHcalOutCellScTile" 
    material = "Hcal/HcalSc"
    sensdet  = "HcalSensDet/Hcal">
    <box name  = "HcalOutCellScTileBox"
      sizeX = "HcalScTileWidth"
      sizeY = "HcalScTileHeigth"
      sizeZ = "HcalScTileLength"/>
    <physvol name = "pvHcalOutCellCalHoleScTile"
      logvol = "/dd/Geometry/DownstreamRegion/Hcal/Cells/lvHcalOutCellCalHoleScTile"> 
      <posXYZ x = "0.0*mm"
              y = "0.0*mm"
              z = "0.0*mm"/>
      <rotXYZ rotY="90*degree"/>
    </physvol>
  </logvol> 
  <!-- **************************************************************** --> 
  <!-- %%%%%%%%%%       Foward Big Inner Spacer              %%%%%%%%%% -->
  <!-- **************************************************************** --> 
  <logvol name = "lvHcalOutCellFwBigSpacer" material = "Hcal/HcalMsPlSteel">
    <box name  = "HcalOutCellFwBigSpacerBox"
      sizeX = "HcalSpacerWidth"
      sizeY = "HcalSpacerHeigth"
      sizeZ = "0.5*HcalSpacerLength+0.5*HcalMsPlStepLength"/>
    <physvol name = "pvHcalOutCellCalHoleFwBigSpacer"
      logvol = "/dd/Geometry/DownstreamRegion/Hcal/Cells/lvHcalOutCellCalHoleSpacer"> 
      <posXYZ x = "0.0*mm"
              y = "0.0*mm"
              z = "-0.25*HcalSpacerLength+0.25*HcalMsPlStepLength"/>
      <rotXYZ rotY="90*degree"/>
    </physvol>
  </logvol> 
  <!-- **************************************************************** --> 
  <!-- %%%%%%%%%%      Foward Small Inner Spacer             %%%%%%%%%% -->
  <!-- **************************************************************** --> 
  <logvol name = "lvHcalOutCellFwSmSpacer" material = "Hcal/HcalMsPlSteel">
      <box name  = "HcalOutCellFwSmSpacerBox"
	sizeX = "HcalSpacerWidth"
	sizeY = "HcalSpacerHeigth"
	sizeZ = "0.5*HcalSpacerLength-0.5*HcalMsPlStepLength"/>
  </logvol> 
  <!-- **************************************************************** --> 
  <!-- %%%%%%%%%%      Backward Big Inner Spacer             %%%%%%%%%% -->
  <!-- **************************************************************** --> 
  <logvol name = "lvHcalOutCellBkBigSpacer" material = "Hcal/HcalMsPlSteel">
    <box name  = "HcalOutCellBkBigSpacerBox"
      sizeX = "HcalSpacerWidth"
      sizeY = "HcalSpacerHeigth"
      sizeZ = "0.5*HcalSpacerLength+0.5*HcalMsPlStepLength"/>
    <physvol name = "pvHcalOutCellCalHoleBkBigSpacer"
      logvol = "/dd/Geometry/DownstreamRegion/Hcal/Cells/lvHcalOutCellCalHoleSpacer"> 
      <posXYZ x = "0.0*mm"
              y = "0.0*mm"
              z = "0.25*HcalSpacerLength-0.25*HcalMsPlStepLength"/>
      <rotXYZ rotY="90*degree"/>
    </physvol>
  </logvol> 
  <!-- **************************************************************** --> 
  <!-- %%%%%%%%%%     Backward Small Inner Spacer            %%%%%%%%%% -->
  <!-- **************************************************************** --> 
  <logvol name = "lvHcalOutCellBkSmSpacer" material = "Hcal/HcalMsPlSteel">
      <box name  = "HcalOutCellBkSmSpacerBox"
	sizeX = "HcalSpacerWidth"
	sizeY = "HcalSpacerHeigth"
	sizeZ = "0.5*HcalSpacerLength-0.5*HcalMsPlStepLength"/>
  </logvol> 
  <!-- **************************************************************** --> 
  <!-- %%%%%%%% Calibration Hole in Master Plates of Outer Cell %%%%%%% -->
  <!-- **************************************************************** --> 
  <logvol name = "lvHcalOutCellCalHoleMsPl" material = "Air">
    <tubs name = "HcalOutCellCalHoleMsPl"
        sizeZ = "HcalMsPlWidth"
        outerRadius = "HcalMsPlCalHoleR"/>
  </logvol> 
  <!-- **************************************************************** --> 
  <!-- %%%%% Calibration Hole in Scintillating Tile of Outer Cell %%%%% -->
  <!-- **************************************************************** --> 
  <logvol name = "lvHcalOutCellCalHoleScTile" material = "Air">
    <tubs name = "HcalOutCellCalHoleScTile"
        sizeZ = "HcalScTileWidth"
        outerRadius = "HcalScTileCalHoleR"/>
  </logvol> 
  <!-- **************************************************************** --> 
  <!-- %%%%%%%%%%  Calibration Hole in Spacers of Outer Cell %%%%%%%%%% -->
  <!-- **************************************************************** --> 
  <logvol name = "lvHcalOutCellCalHoleSpacer" material = "Air">
    <tubs name = "HcalOutCellCalHoleSpacer"
        sizeZ = "HcalSpacerWidth"
        outerRadius = "HcalMsPlCalHoleR"/>
  </logvol> 
  <!-- **************************************************************** --> 
</DDDB>

=== pseyfertinsecurelogin/LHCb/Ex/DetCondExample/XMLDDDB/Ecal/Installation/BeamPlug.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DDDB SYSTEM "../../DTD/geometry.dtd">
<DDDB>


  <logvol name = "PlugSupport" material = "Ecal/EcalPb">
    <subtraction name = "PlugWithHole">
      <box name  = "Plugbox"
        sizeX       = "EcalBeamPlugXSize"
        sizeY       = "EcalBeamPlugYSize"
        sizeZ       = "EcalBeamPlugZSize"/>
      <polycone name="PipeHole"
                startPhiAngle="0*degree"
                deltaPhiAngle="360*degree">
		<zplane innerRadius="0.0*mm" outerRadius="EcalBeamPlugPipeHoleR1" z="EcalBeamPlugPipeHoleZ1"/>
		<zplane innerRadius="0.0*mm" outerRadius="EcalBeamPlugPipeHoleR2" z="EcalBeamPlugPipeHoleZ2"/>
		<zplane innerRadius="0.0*mm" outerRadius="EcalBeamPlugPipeHoleR3" z="EcalBeamPlugPipeHoleZ3"/>
		<zplane innerRadius="0.0*mm" outerRadius="EcalBeamPlugPipeHoleR4" z="EcalBeamPlugPipeHoleZ4"/>
		<zplane innerRadius="0.0*mm" outerRadius="EcalBeamPlugPipeHoleR5" z="EcalBeamPlugPipeHoleZ5"/>
		<zplane innerRadius="0.0*mm" outerRadius="EcalBeamPlugPipeHoleR6" z="EcalBeamPlugPipeHoleZ6"/>
      </polycone>
      <posXYZ x = "0.0*mm"
              y = "-EcalYShift"
              z = "0.0*mm"/>
      <rotXYZ rotX="-EcalTiltAngle"/>
    </subtraction>

    <paramphysvol number = "2">
      <physvol name = "HAirSlots"  
               logvol = "/dd/Geometry/DownstreamRegion/Ecal/Installation/HorizontalAirSlot">
        <posXYZ y = "-0.5*(EcalBeamPlugYSize-EcalSteelSheetThick1)"
                z = " 0.5*EcalSteelSheetLength1"/>
      </physvol>
      <posXYZ y = "EcalBeamPlugYSize-EcalSteelSheetThick1"/>
    </paramphysvol>

    <paramphysvol number = "2">
    <physvol name = "VAirSlots"  
             logvol = "/dd/Geometry/DownstreamRegion/Ecal/Installation/VerticalAirSlot">
      <posXYZ x = "-0.5*(EcalBeamPlugXSize-EcalSteelSheetThick1)"
              z = " 0.5*EcalSteelSheetLength1"/>
    </physvol>
      <posXYZ x = "EcalBeamPlugYSize-EcalSteelSheetThick1"/>
    </paramphysvol>

    <paramphysvol number = "2">
      <physvol name = "VSteelSheets1"  
               logvol = "/dd/Geometry/DownstreamRegion/Ecal/Installation/VericalSteelSheet1">
        <posXYZ x = "-0.5*(EcalBeamPlugXSize-EcalSteelSheetThick1)"
                z = "-0.5*(EcalBeamPlugZSize-EcalSteelSheetLength1)"/>
      </physvol>
      <posXYZ x = "EcalBeamPlugXSize-EcalSteelSheetThick1"/>
    </paramphysvol>
      
    <paramphysvol number = "2">
      <physvol name = "HSteelSheets1"  
               logvol = "/dd/Geometry/DownstreamRegion/Ecal/Installation/HorizontalSteelSheet1">
        <posXYZ y = "-0.5*(EcalBeamPlugYSize-EcalSteelSheetThick1)"
                z = "-0.5*(EcalBeamPlugZSize-EcalSteelSheetLength1)"/>
      </physvol>
      <posXYZ y = "EcalBeamPlugYSize-EcalSteelSheetThick1"/>
    </paramphysvol>
    
    <paramphysvol number = "2">
      <physvol name = "VSteelSheets2"  
               logvol = "/dd/Geometry/DownstreamRegion/Ecal/Installation/VericalSteelSheet2">
        <posXYZ x = "-0.5*EcalBeamPlugXSize+0.5*EcalSteelSheetThick2+EcalSteelSheetThick1"
                z = " 0.5*(EcalBeamPlugZSize-EcalSteelSheetLength2)"/>
      </physvol>
      <posXYZ x = "EcalBeamPlugXSize-EcalSteelSheetThick2-2*EcalSteelSheetThick1"/>
    </paramphysvol>
      
    <paramphysvol number = "2">
      <physvol name = "HSteelSheets2"  
               logvol = "/dd/Geometry/DownstreamRegion/Ecal/Installation/HorizontalSteelSheet2">
        <posXYZ y = "-0.5*EcalBeamPlugYSize+0.5*EcalSteelSheetThick2+EcalSteelSheetThick1"
                z = " 0.5*(EcalBeamPlugZSize-EcalSteelSheetLength2)"/>
      </physvol>
      <posXYZ y = "EcalBeamPlugYSize-EcalSteelSheetThick2-2*EcalSteelSheetThick1"/>
    </paramphysvol>

    <paramphysvol number = "2">
      <physvol name = "SteelSheets1"  
               logvol = "/dd/Geometry/DownstreamRegion/Ecal/Installation/SteelSheetWithHole1">
        <posXYZ z = " 0.5*(EcalBeamPlugZSize-EcalSteelSheetWithHoleThick1)"/>
      </physvol>
      <posXYZ z = "-EcalSteelSheetWithHoleStep1"/>
    </paramphysvol>
    <paramphysvol number = "3">
      <physvol name = "SteelSheets2"  
               logvol = "/dd/Geometry/DownstreamRegion/Ecal/Installation/SteelSheetWithHole2">
        <posXYZ z = " 0.5*EcalBeamPlugZSize-EcalSteelSheetLength2-0.5*EcalSteelSheetWithHoleThick2"/>
      </physvol>
      <posXYZ z = "-EcalSteelSheetWithHoleStep2"/>
    </paramphysvol>

  </logvol> 
 
  <logvol name = "HorizontalAirSlot " material = "Air">
    <box name  = "HAirSlot"
      sizeX       = "EcalBeamPlugXSize"
      sizeY       = "EcalSteelSheetThick1"
      sizeZ       = "EcalBeamPlugZSize-EcalSteelSheetLength1"/>
  </logvol>
  
  <logvol name = "VerticalAirSlot " material = "Air">
    <box name  = "VAirSlot"
      sizeX       = "EcalSteelSheetThick1"
      sizeY       = "EcalBeamPlugYSize-2*EcalSteelSheetThick1"
      sizeZ       = "EcalBeamPlugZSize-EcalSteelSheetLength1"/>
  </logvol>
  
  <logvol name = "VericalSteelSheet1 " material = "Ecal/EcalSteel">
    <box name  = "VSteelSheet1"
      sizeX       = "EcalSteelSheetThick1-EcalDelta"
      sizeY       = "EcalBeamPlugYSize-EcalDelta"
      sizeZ       = "EcalSteelSheetLength1-EcalDelta"/>
  </logvol> 
  <logvol name = "HorizontalSteelSheet1 " material = "Ecal/EcalSteel">
    <box name  = "HSteelSheet1"
      sizeX       = "EcalBeamPlugXSize - 2*EcalSteelSheetThick1-EcalDelta"
      sizeY       = "EcalSteelSheetThick1-EcalDelta"
      sizeZ       = "EcalSteelSheetLength1-EcalDelta"/>
  </logvol> 
  <logvol name = "VericalSteelSheet2 " material = "Ecal/EcalSteel">
    <box name  = "VSteelSheet2"
      sizeX       = "EcalSteelSheetThick2"
      sizeY       = "EcalBeamPlugYSize-2*EcalSteelSheetThick1"
      sizeZ       = "EcalSteelSheetLength2"/>
  </logvol> 
  <logvol name = "HorizontalSteelSheet2 " material = "Ecal/EcalSteel">
    <box name  = "HSteelSheet2"
      sizeX       = "EcalBeamPlugXSize-2*EcalSteelSheetThick1-2*EcalSteelSheetThick2-EcalDelta"
      sizeY       = "EcalSteelSheetThick2-EcalDelta"
      sizeZ       = "EcalSteelSheetLength2-EcalDelta"/>
  </logvol> 
  <logvol name = "SteelSheetWithHole1 " material = "Ecal/EcalSteel">
    <subtraction name = "StSheetWithHole1">
      <box name  = "StSheet1"
        sizeX       = "EcalBeamPlugXSize-2*EcalSteelSheetThick1-2*EcalSteelSheetThick2-EcalDelta"
        sizeY       = "EcalBeamPlugYSize-2*EcalSteelSheetThick1-2*EcalSteelSheetThick2-EcalDelta"
        sizeZ       = "EcalSteelSheetWithHoleThick1-EcalDelta"/>
      <tubs name  = "CylinderHole1"
        sizeZ       = "EcalSteelSheetWithHoleThick1+10*mm"
        outerRadius = "EcalSteelSheetWithHoleRadius1"/>
    </subtraction>
  </logvol> 
  <logvol name = "SteelSheetWithHole2 " material = "Ecal/EcalSteel">
    <subtraction name = "StSheetWithHole2">
      <box name  = "StSheet2"
        sizeX       = "EcalBeamPlugXSize-2*EcalSteelSheetThick1-EcalDelta"
        sizeY       = "EcalBeamPlugYSize-2*EcalSteelSheetThick1-EcalDelta"
        sizeZ       = "EcalSteelSheetWithHoleThick1-EcalDelta"/>
      <tubs name  = "CylinderHole2"
        sizeZ       = "EcalSteelSheetWithHoleThick2+10*mm"
        outerRadius = "EcalSteelSheetWithHoleRadius2"/>
    </subtraction>
  </logvol> 

  
  
  
  
  <!-- **************************************************************** --> 
</DDDB>

=== pseyfertinsecurelogin/LHCb/Ex/DetCondExample/XMLDDDB/Ecal/Modules/InnCell.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DDDB SYSTEM "../../DTD/geometry.dtd">
<DDDB>
<!-- """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" --> 
<!--   
  CVS tag: $Name: not supported by cvs2svn $
  $Log: not supported by cvs2svn $
  Revision 1.1.1.1  2007/01/30 13:34:59  marcocle
  CVS based back up for the SQLite conditions database

  Revision 1.7  2006/02/06 15:54:00  cattanem
  DC06 geometry and cleanup of older stuff

  Revision 1.6  2005/06/06 15:59:43  gcorti
  Calo tilt

  Revision 1.5  2003/07/10 14:56:28  cattanem
  changes for v17r0 - see release notes

  Revision 1.4  2003/06/19 06:18:22  cattanem
  v16r0

  Revision 1.3  2002/09/12 09:32:58  cattanem
  Add vertical Rich, Velo optimisation

  Revision 1.2  2002/01/19 13:58:42  ibelyaev
   fix the bug with material names/paths

  Revision 1.1  2001/12/15 16:05:37  ibelyaev
  The first version of  detailed Ecal description by Galina Pakhlova
 
--> 
<!-- """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""" --> 
<!-- ****************************************************************** --> 
<!--                     Ecal Inner Cell Geometry                       -->
<!--                    Logical Volumes Definition                      --> 
<!-- ****************************************************************** --> 

 <logvol name = "InnCell" material = "Ecal/EcalSc" sensdet="EcalSensDet/Ecal">
         <box  name  = "Inner_Cell_Main_Box"
               sizeX = "EcalInnCellXYSize"
               sizeY = "EcalInnCellXYSize"
               sizeZ = "EcalStackLength"/>

<!-- %%%  Front Steel Matrix Installation into Inner Cell %%%  -->
                        
      <physvol name   = "InnFrontSteelMatrix"
               logvol = "/dd/Geometry/DownstreamRegion/Ecal/Modules/InnCellSteel">
                  <posXYZ z = "EcalSteelOffset"/>
      </physvol>

<!-- %%%  Back Steel Matrix Installation into Inner Cell %%%  -->

      <physvol name   = "InnBackSteelMatrix"
               logvol = "/dd/Geometry/DownstreamRegion/Ecal/Modules/InnCellSteel">
                  <posXYZ z = "-1*EcalSteelOffset"/>
      </physvol>

<!-- %%%  Front Plastic Installation into Inner Cell %%%  --> 
                                      
      <physvol name   = "InnFrontPlastic"
               logvol = "/dd/Geometry/DownstreamRegion/Ecal/Modules/InnCellPlastic">
                   <posXYZ  z = "EcalPlasticOffset"/>
      </physvol>

<!-- %%%  Back Plastic Installation into Inner Cell %%%  --> 
 
      <physvol name   = "InnBackPlastic"
               logvol = "/dd/Geometry/DownstreamRegion/Ecal/Modules/InnCellPlastic">
                  <posXYZ   z = "-1*EcalPlasticOffset"/>
      </physvol>

<!-- %%%  Pb Cells Installation into Inner Cell %%%  --> 

        <paramphysvol number = "66">
          <physvol name   = "Inner_Pb_Cells"
                   logvol = "/dd/Geometry/DownstreamRegion/Ecal/Modules/InnCellPb">
                       <posXYZ   z = "EcalPbOffset"/>
          </physvol>
               <posXYZ  z = "EcalScThick + EcalPbThick + 2*EcalPaperThick"/>
        </paramphysvol>

 </logvol>
<!-- ****************************************************************** --> 
</DDDB>
