=== pseyfertinsecurelogin/LHCb/Event/DAQEvent/tests/data/runchangehandler/structure.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Minimal version of structure.dtd for tests. -->
<!-- The complete version is available at conddb:/DTD/structure.dtd -->
<!-- Author: Marco Clemencic -->


<!--DDDB: XML root element, Gaudi transient store root as well-->
<!ELEMENT DDDB ( catalog| catalogref | condition )+>
<!ATTLIST DDDB version CDATA "3.3" >

<!--
param: this allows the user to add a parameter, giving its name, type and
       possibly a comment. This parameter will then be reachable through the
       getUserParam method of the resulting detector element. Note that the
       default type is "double" and the default comment is empty.
-->
<!ELEMENT param (#PCDATA)>
<!ATTLIST param xml:space (default|preserve) #FIXED "preserve"
  type CDATA "double"
  name CDATA #REQUIRED
  comment CDATA "">

<!-- 
paramVector: This is an equivalent of userParam but it defines a vector of
             values. Note that the vector has no given size. The parser will
             take every value it finds. These should be separated by spaces
             and/or cariage returns
-->
<!ELEMENT paramVector (#PCDATA)>
<!ATTLIST paramVector xml:space (default|preserve) #FIXED "preserve"
  type CDATA "double"
  name CDATA #REQUIRED
  comment CDATA "">

<!-- Element used to declare one item in a map -->
<!ELEMENT item EMPTY>
<!ATTLIST item
  key   CDATA #REQUIRED
  value CDATA #REQUIRED>

<!-- Element to define a map in a condition object -->
<!ELEMENT map (item*)>
<!ATTLIST map xml:space (default|preserve) #FIXED "preserve"
  keytype   CDATA "string"
  valuetype CDATA "double"
  name      CDATA #REQUIRED
  comment   CDATA "">

<!ELEMENT specific ANY>

<!--
condition: This defines a condition in a very generic way.
           It is actually a set of parameters and it may have optional
           user defined custom data, its specific information
-->
<!ELEMENT condition (( param | paramVector | map | specific )*)>

<!--condition: name and classID-->
<!ATTLIST condition
  name ID #REQUIRED 
  classID CDATA "5">

<!--
conditionref: reference to detector element data location.
              The form of URI is either to refer outside(1) or inside(2) a file
                 1) href="protocol://HOSTNAME/path/to/file.xml#catalogID"
                 2) href="#catalogID"   
-->
<!ELEMENT conditionref EMPTY>
<!ATTLIST conditionref
  href CDATA #REQUIRED
>

<!--
catalog: helps to define a partition of XML dB for domain specific part
         and flat store, e.g. a palette of detector elements
-->
<!ELEMENT catalog ( catalog     | catalogref     |
                    condition   | conditionref   )*>
<!--
catalog : name
-->
<!ATTLIST catalog
  name ID #REQUIRED>
<!--
catalogref: refer to the location where the actual catalog data reside
-->
<!ELEMENT catalogref EMPTY>
<!--
catalogref: name 
            href : the actual URI of the catalog location the form of URI is
                   either to refer outside(1) or inside(2) a file
                      1) href="protocol://HOSTNAME/path/to/file.xml#catalogID"
                      2) href="#catalogID"
-->
<!ATTLIST catalogref
  href CDATA #REQUIRED>

=== pseyfertinsecurelogin/LHCb/Ex/DetCondExample/XMLDDDB/Conditions/Hcal/ReadoutConf/Main.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE DDDB SYSTEM "../../../DTD/structure.dtd">
<DDDB>

  <condition name = "Hardware">
    <param name = "AdcMax"        type = "int"    >  4095 </param>
    <param name = "CodingBit"     type = "int"    >     5 </param>
    <param name = "centralHoleX"  type = "int"    >     2 </param>
    <param name = "centralHoleY"  type = "int"    >     2 </param>
  </condition>
  <condition name = "CellsToCards">
    <paramVector name = "cards" type = "int">

<!---   #  a  cf  rf  cl  rl   cr sl -->
        <!---  Outer area -->

        0  0   0   1   7   4   22  2
        1  0   0   5   7   8   22  3
        2  0   0   9   7  12   22  4
        3  0   0  13   7  16   22  5
        4  0   0  17   7  20   22  6
        5  0   0  21   7  24   22  7
        6  0   0  25   7  28   22  8
        7  0   8   1  15   4   22  9
        8  0   8   5  15   8   22 10
        9  0   8  21  15  24   22 11
       10  0   8  25  15  28   22 12

       11  1   0   2   7   5   23  1
       12  1   0   6   7   9   23  2
       13  1   0  10   7  13   23  3
       14  1   0  14   7  17   23  4
       15  1   0  18   7  21   23  5
       16  1   0  22   7  25   23  6
       17  1   0  26   7  29   23  7
       18  1   8   2  15   5   23  8
       19  1   8   6  15   9   23  9
       20  1   8  10  15  13   23 10
       21  1   8  14  15  17   23 11
       22  1   8  18  15  21   23 12
       23  1   8  22  15  25   23 13
       24  1   8  26  15  29   23 14

       25  1  16   2  23   5   24  1
       26  1  16   6  23   9   24  2
       27  1  16  10  23  13   24  3
       28  1  16  14  23  17   24  4
       29  1  16  18  23  21   24  5
       30  1  16  22  23  25   24  6
       31  1  16  26  23  29   24  7
       32  1  24   2  31   5   24  8
       33  1  24   6  31   9   24  9
       34  1  24  10  31  13   24 10
       35  1  24  14  31  17   24 11
       36  1  24  18  31  21   24 12
       37  1  24  22  31  25   24 13
       38  1  24  26  31  29   24 14

       39  0  16   1  23   4   25  2
       40  0  16   5  23   8   25  3
       41  0  16  21  23  24   25  4
       42  0  16  25  23  28   25  5
       43  0  24   1  31   4   25  6 
       44  0  24   5  31   8   25  7
       45  0  24   9  31  12   25  8
       46  0  24  13  31  16   25  9
       47  0  24  17  31  20   25 10
       48  0  24  21  31  24   25 11
       49  0  24  25  31  28   25 12

    </paramVector>
    <paramVector name = "Tell1" type = "int">

        0  6    0   1   2   3   4   5
        1  5    6   7   8   9  10
        2  7   11  12  13  14  15  16  17
        3  7   18  19  20  21  22  23  24 
        4  7   25  26  27  28  29  30  31 
        5  7   32  33  34  35  36  37  38 
        6  6   39  40  41  42  43  44
        7  5   45  46  47  48  49

    </paramVector>
  </condition>

</DDDB>

=== pseyfertinsecurelogin/LHCb/Det/VeloDet/tests/data/alignment.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE DDDB SYSTEM "structure.dtd">
<DDDB>
	<catalog name="Alignment">
		<catalog name="Velo">
			<condition name="VeloLeft" classID="1008106">
				<paramVector name="dPosXYZ" type="double">0 0 0</paramVector>
				<paramVector name="dRotXYZ" type="double">0 0 0</paramVector>
				<paramVector name="pivotXYZ" type="double">0 0 0</paramVector>
				<param name="XOffset" type="string">Conditions/Online/Velo/MotionSystem[ResolPosLA]</param>
				<param name="YOffset" type="string">Conditions/Online/Velo/MotionSystem[ResolPosY]</param>
			</condition>
			<condition name="VeloRight" classID="1008106">
				<paramVector name="dPosXYZ" type="double">0 0 0</paramVector>
				<paramVector name="dRotXYZ" type="double">0 0 0</paramVector>
				<paramVector name="pivotXYZ" type="double">0 0 0</paramVector>
				<param name="XOffset" type="string">Conditions/Online/Velo/MotionSystem[ResolPosRC]</param>
				<param name="YOffset" type="string">Conditions/Online/Velo/MotionSystem[ResolPosY]</param>
				<!-- Being YOffset == 1, we should get 15  -->
				<paramVector name="YOffsetCoeffs" type="double">20 -5</paramVector>
			</condition>
		</catalog>
	</catalog>
</DDDB>

=== pseyfertinsecurelogin/LHCb/Ex/DetCondExample/XMLDDDB/Conditions/MainCatalog.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE DDDB SYSTEM "../DTD/structure.dtd">
<DDDB>

  <catalog name="Conditions">
    <catalogref href = "#Alignment"/>
    <catalogref href = "#Calibration"/>
    <catalogref href = "#ChannelInfo"/>
    <catalogref href = "#Environment"/>
    <catalogref href = "#HardwareProperties"/>
    <catalogref href = "#ReadoutConf"/>
    <catalogref href = "Trigger/Catalog.xml#Trigger"/>
    <catalogref href = "#Sim"/>
  </catalog>

  <catalog name="Alignment">
    <catalogref href = "LHCb/AlignmentCatalog.xml#LHCb"/>
    <catalogref href = "Velo/AlignmentCatalog.xml#Velo"/>
    <!--
    <catalogref href = "TT/AlignmentCatalog.xml#TT"/>
    <catalogref href = "Rich1/AlignmentCatalog.xml#Rich1"/>
    <catalogref href = "IT/AlignmentCatalog.xml#IT"/>
    <catalogref href = "OT/AlignmentCatalog.xml#OT"/>
    <catalogref href = "Rich2/AlignmentCatalog.xml#Rich2"/>
    <catalogref href = "Prs/AlignmentCatalog.xml#Prs"/>
    -->
    <catalogref href = "Ecal/AlignmentCatalog.xml#Ecal"/>
    <catalogref href = "Hcal/AlignmentCatalog.xml#Hcal"/>
    <!--
    <catalogref href = "Muon/AlignmentCatalog.xml#Muon"/>
    -->
  </catalog>

  <catalog name="Calibration">
    <!--
    <catalogref href = "Spd/CalibrationCatalog.xml#Spd"/>
    <catalogref href = "Prs/CalibrationCatalog.xml#Prs"/>
    -->
    <catalogref href = "Ecal/CalibrationCatalog.xml#Ecal"/>
    <catalogref href = "Hcal/CalibrationCatalog.xml#Hcal"/>
    <!--
    <catalogref href = "Muon/CalibrationCatalog.xml#Muon"/>
    -->
  </catalog>

  <catalog name="ChannelInfo">
    <!-- <catalogref href="Velo/ChannelInfoCatalog.xml#Velo"/> -->
  </catalog>
  
  <catalog name="Environment">
    <catalogref href = "LHCb/EnvironmentCatalog.xml#LHCb"/>
    <!--
    <catalogref href = "Rich1/EnvironmentCatalog.xml#Rich1"/>
    <catalogref href = "Rich2/EnvironmentCatalog.xml#Rich2"/>
    -->
  </catalog>
  
  <catalog name="HardwareProperties">
    <!-- <catalogref href="Velo/HardwarePropertiesCatalog.xml#Velo"/> -->
  </catalog>
  
  <catalog name="ReadoutConf">
    <!--
    <catalogref href = "Velo/ReadoutConfCatalog.xml#Velo"/>
    <catalogref href = "TT/ReadoutConfCatalog.xml#TT"/>
    <catalogref href = "IT/ReadoutConfCatalog.xml#IT"/>
    <catalogref href = "Spd/ReadoutConfCatalog.xml#Spd"/>
    <catalogref href = "Prs/ReadoutConfCatalog.xml#Prs"/>
    -->
    <catalogref href = "Ecal/ReadoutConfCatalog.xml#Ecal"/>
    <catalogref href = "Hcal/ReadoutConfCatalog.xml#Hcal"/>
    <!--
    <catalogref href = "Muon/ReadoutConfCatalog.xml#Muon"/>
    <catalogref href = "Rich1/ReadoutConfCatalog.xml#Rich1"/>
    <catalogref href = "Rich2/ReadoutConfCatalog.xml#Rich2"/>
    -->
  </catalog>

  <catalog name="Sim">
    <condition name="TestCondition">
      <paramVector comment="List of layers" name="layers" type="string">TTaXMap TTaUMap TTbVMap TTbXMap</paramVector>
      <paramVector name="vs" type="string">
        str1
        str2 str3 str4</paramVector>
    </condition>
  </catalog>

</DDDB>

=== pseyfertinsecurelogin/LHCb/Ex/DetCondExample/XMLDDDB/Conditions/Velo/AlignmentCatalog.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE DDDB SYSTEM "../../DTD/structure.dtd">
<DDDB>
  <catalog name ="Velo">
    <conditionref href="Alignment/Global.xml#VeloSystem"/>
    <conditionref href="Alignment/Global.xml#VeloRight"/>
    <conditionref href="Alignment/Global.xml#VeloLeft"/>

    <conditionref href="Alignment/Modules.xml#ModulePU00"/>
    <conditionref href="Alignment/Modules.xml#ModulePU01"/>
    <conditionref href="Alignment/Modules.xml#ModulePU02"/>
    <conditionref href="Alignment/Modules.xml#ModulePU03"/>
    <conditionref href="Alignment/Modules.xml#Module00"/>
    <conditionref href="Alignment/Modules.xml#Module01"/>
    <conditionref href="Alignment/Modules.xml#Module02"/>
    <conditionref href="Alignment/Modules.xml#Module03"/>
    <conditionref href="Alignment/Modules.xml#Module04"/>
    <conditionref href="Alignment/Modules.xml#Module05"/>
    <conditionref href="Alignment/Modules.xml#Module06"/>
    <conditionref href="Alignment/Modules.xml#Module07"/>
    <conditionref href="Alignment/Modules.xml#Module08"/>
    <conditionref href="Alignment/Modules.xml#Module09"/>
    <conditionref href="Alignment/Modules.xml#Module10"/>
    <conditionref href="Alignment/Modules.xml#Module11"/>
    <conditionref href="Alignment/Modules.xml#Module12"/>
    <conditionref href="Alignment/Modules.xml#Module13"/>
    <conditionref href="Alignment/Modules.xml#Module14"/>
    <conditionref href="Alignment/Modules.xml#Module15"/>
    <conditionref href="Alignment/Modules.xml#Module16"/>
    <conditionref href="Alignment/Modules.xml#Module17"/>
    <conditionref href="Alignment/Modules.xml#Module18"/>
    <conditionref href="Alignment/Modules.xml#Module19"/>
    <conditionref href="Alignment/Modules.xml#Module20"/>
    <conditionref href="Alignment/Modules.xml#Module21"/>
    <conditionref href="Alignment/Modules.xml#Module22"/>
    <conditionref href="Alignment/Modules.xml#Module23"/>
    <conditionref href="Alignment/Modules.xml#Module24"/>
    <conditionref href="Alignment/Modules.xml#Module25"/>
    <conditionref href="Alignment/Modules.xml#Module26"/>
    <conditionref href="Alignment/Modules.xml#Module27"/>
    <conditionref href="Alignment/Modules.xml#Module28"/>
    <conditionref href="Alignment/Modules.xml#Module29"/>
    <conditionref href="Alignment/Modules.xml#Module30"/>
    <conditionref href="Alignment/Modules.xml#Module31"/>
    <conditionref href="Alignment/Modules.xml#Module32"/>
    <conditionref href="Alignment/Modules.xml#Module33"/>
    <conditionref href="Alignment/Modules.xml#Module34"/>
    <conditionref href="Alignment/Modules.xml#Module35"/>
    <conditionref href="Alignment/Modules.xml#Module36"/>
    <conditionref href="Alignment/Modules.xml#Module37"/>
    <conditionref href="Alignment/Modules.xml#Module38"/>
    <conditionref href="Alignment/Modules.xml#Module39"/>
    <conditionref href="Alignment/Modules.xml#Module40"/>
    <conditionref href="Alignment/Modules.xml#Module41"/>
    
    <conditionref href="Alignment/Detectors.xml#DetectorPU00-00"/>
    <conditionref href="Alignment/Detectors.xml#DetectorPU01-00"/>
    <conditionref href="Alignment/Detectors.xml#DetectorPU02-00"/>
    <conditionref href="Alignment/Detectors.xml#DetectorPU03-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector00-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector00-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector01-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector01-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector02-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector02-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector03-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector03-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector04-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector04-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector05-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector05-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector06-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector06-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector07-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector07-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector08-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector08-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector09-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector09-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector10-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector10-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector11-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector11-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector12-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector12-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector13-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector13-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector14-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector14-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector15-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector15-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector16-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector16-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector17-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector17-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector18-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector18-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector19-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector19-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector20-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector20-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector21-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector21-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector22-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector22-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector23-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector23-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector24-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector24-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector25-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector25-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector26-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector26-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector27-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector27-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector28-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector28-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector29-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector29-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector30-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector30-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector31-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector31-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector32-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector32-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector33-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector33-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector34-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector34-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector35-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector35-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector36-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector36-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector37-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector37-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector38-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector38-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector39-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector39-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector40-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector40-01"/>
    <conditionref href="Alignment/Detectors.xml#Detector41-00"/>
    <conditionref href="Alignment/Detectors.xml#Detector41-01"/>
  </catalog>
</DDDB>

=== pseyfertinsecurelogin/LHCb/Ex/DetCondExample/XMLDDDB/Velo/alignment.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DDDB SYSTEM "../DTD/structure.dtd">
<!-- $Id: alignment.xml,v 1.1 2005-08-31 16:02:49 marcocle Exp $ -->
<DDDB>
  <catalog name ="Velo">
    <conditionref href="conddb:/Alignment/Velo/Modules:00#Module00"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:01#Module01"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:02#Module02"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:03#Module03"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:04#Module04"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:05#Module05"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:06#Module06"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:07#Module07"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:08#Module08"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:09#Module09"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:10#Module10"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:11#Module11"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:12#Module12"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:13#Module13"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:14#Module14"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:15#Module15"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:16#Module16"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:17#Module17"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:18#Module18"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:19#Module19"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:20#Module20"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:21#Module21"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:22#Module22"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:23#Module23"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:24#Module24"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:25#Module25"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:26#Module26"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:27#Module27"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:28#Module28"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:29#Module29"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:30#Module30"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:31#Module31"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:32#Module32"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:33#Module33"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:34#Module34"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:35#Module35"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:36#Module36"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:37#Module37"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:38#Module38"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:39#Module39"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:40#Module40"/>
    <conditionref href="conddb:/Alignment/Velo/Modules:41#Module41"/>
  </catalog>
</DDDB>

=== pseyfertinsecurelogin/LHCb/Ex/DetCondExample/XMLDDDB/Conditions/Velo/Alignment/Global.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
    (c) Copyright 2000-2018 CERN for the benefit of the LHCb Collaboration

    This software is distributed under the terms of the GNU General Public
    Licence version 3 (GPL Version 3), copied verbatim in the file "COPYING".

    In applying this licence, CERN does not waive the privileges and immunities
    granted to it by virtue of its status as an Intergovernmental Organization
    or submit itself to any jurisdiction.
-->
<!DOCTYPE DDDB SYSTEM "../../../DTD/structure.dtd" >
<DDDB>

  <condition classID="6" name="VeloSystem">
    <paramVector name="dPosXYZ" type="double">0 0 0</paramVector>
    <paramVector name="dRotXYZ" type="double">0 0 0</paramVector>
  </condition>

  <condition classID="6" name="VeloRight">
    <paramVector name="dPosXYZ" type="double">0 0 0</paramVector>
    <paramVector name="dRotXYZ" type="double">0 0 0</paramVector>
    <paramVector name="pivotXYZ" type="double">0 0 0</paramVector>
  </condition>

  <condition classID="6" name="VeloLeft">
    <paramVector name="dPosXYZ" type="double">0 0 0</paramVector>
    <paramVector name="dRotXYZ" type="double">0 0 0</paramVector>
    <paramVector name="pivotXYZ" type="double">0 0 0</paramVector>
  </condition>

</DDDB>
