=== pseyfertinsecurelogin/LHCb/Kernel/XMLSummaryBase/xml/XMLSummary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- This is the XML schema for the Gaudi XML Summary -->
<!-- The version of the schema appears in the summary, and must be edited in each version -->


<!-- The summary element is the only pre-defined element -->
<!-- This is the root element of the schema -->

    <xs:element name="summary" type="SummaryType"/>

<!-- This version attribute holds the version of the schema, which may change -->
<!-- it is written such that new objects cannot be parsed with an older schema -->

	<xs:attribute name="version" default="1.0">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:whiteSpace value="collapse"/>
				<xs:enumeration value="1.0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

<!-- We start with defining the simple types -->

	<xs:simpleType name="CollapsedString">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:attribute name="min" type="xs:double" default="0.0"/>
	<xs:attribute name="max" type="xs:double" default="0.0"/>
	
	<xs:simpleType name="StepType">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:enumeration value="none"/>
			<xs:enumeration value="initialize"/>
			<xs:enumeration value="execute"/>
			<xs:enumeration value="finalize"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="FileStatus">
    	<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
    		<xs:enumeration value="none"/>
    		<xs:enumeration value="fail"/>
    		<xs:enumeration value="part"/>
    		<xs:enumeration value="full"/>
    		<xs:enumeration value="mult"/>
    	</xs:restriction>
    </xs:simpleType>


	<xs:simpleType name="UsageOption">
    	<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
    		<xs:enumeration value="MemoryMaximum"/>
    	</xs:restriction>
    </xs:simpleType>

	<xs:simpleType name="FormatType">
    	<xs:list itemType="xs:string"/>
    </xs:simpleType>
    
	<xs:simpleType name="StatType">
    	<xs:list itemType="xs:double"/>
    </xs:simpleType>

	<xs:simpleType name="StatOption">
    	<xs:restriction base="FormatType">
			<xs:whiteSpace value="collapse"/>
    		<xs:enumeration value="Flag Entries Flag2"/>
    		<xs:enumeration value="Flag Flag2 Entries"/>
    		<xs:enumeration value="Flag2 Flag Entries"/>
    		<xs:enumeration value="Flag2 Entries Flag"/>
    		<xs:enumeration value="Entries Flag2 Flag"/>
    		<xs:enumeration value="Entries Flag Flag2"/>
    	</xs:restriction>
    </xs:simpleType>


<!-- Now we define the attributes based on the enums -->

	<xs:attribute name="status" type="FileStatus" default="none"/>
	<xs:attribute name="useOf" type="UsageOption" default="MemoryMaximum"/>
	<xs:attribute name="format" type="StatOption" default="Flag Entries Flag2"/>
	
<!-- Now we define the counter types -->

    <xs:complexType name="UsageSummary">
    	<xs:simpleContent>
    		<xs:extension base="xs:double">
    			<xs:attribute ref="useOf" use="required"/>
    			<xs:attribute name="unit" type="CollapsedString" use="required"/>
    		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>


    <xs:complexType name="Count">
    	<xs:simpleContent>
    		<xs:extension base="xs:long">
    			<xs:attribute name="name" use="required" type="CollapsedString"/>
    		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>
    
    <xs:complexType name="StatCount">
    	<xs:simpleContent>
    		<xs:extension base="StatType">
    			<xs:attribute ref="format" use="required"/>
    			<xs:attribute name="name" use="required" type="CollapsedString" />
    			<xs:attribute ref="min" use="required" />
    			<xs:attribute ref="max" use="required" />
    		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>
    

    <xs:complexType name="FileCount">
    	<xs:simpleContent>
    		<xs:extension base="xs:long">
    			<xs:attribute name="GUID" type="CollapsedString" use="required"/>
    			<xs:attribute name="name" type="CollapsedString" use="required"/>
    			<xs:attribute ref="status" use="required"/>
    		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>


<!-- Now we define the types with sequences of counters -->

    <xs:complexType name="Usage">
    	<xs:sequence>
    		<xs:element name="stat" type="UsageSummary"  minOccurs="0" maxOccurs="unbounded" default="0.0"/>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Counts">
    	<xs:sequence>
    		<xs:element name="counter" type="Count"  minOccurs="0" maxOccurs="unbounded" default="0"/>
    		<xs:element name="statEntity" type="StatCount"  minOccurs="0" maxOccurs="unbounded" default="0.0 0 0.0"/>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="FileCounts">
    	<xs:sequence>
    		<xs:element name="file" type="FileCount"  minOccurs="0" maxOccurs="unbounded" default="0"/>
    	</xs:sequence>
    </xs:complexType>
    

<!-- The summary type is the overall structure of the file -->

    <xs:complexType name="SummaryType">
    	<xs:sequence>
    		<xs:element name="success"  type="xs:boolean" 	minOccurs="1"	maxOccurs="1" default="false"/>
    		<xs:element name="step" 	type="StepType" 	minOccurs="1" 	maxOccurs="1" />
    		<xs:element name="usage" 	type="Usage" 		minOccurs="1" 	maxOccurs="1" />
    		<xs:element name="input" 	type="FileCounts" 	minOccurs="1" 	maxOccurs="1" />
    		<xs:element name="output" 	type="FileCounts" 	minOccurs="1" 	maxOccurs="1" />
    		<xs:element name="counters"     type="Counts" 		minOccurs="1" 	maxOccurs="1" />
    		<xs:element name="lumiCounters" type="Counts"           minOccurs="1"   maxOccurs="1" />
    	</xs:sequence>
    	<xs:attribute ref="version"  use="required"/>
    </xs:complexType>


</xs:schema>

=== pseyfertinsecurelogin/LHCb/Kernel/FSRAlgs/tests/qmtest/summary.xml
<?xml version="1.0" encoding="UTF-8"?>

<summary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:noNamespaceSchemaLocation="$XMLSUMMARYBASEROOT/xml/XMLSummary.xsd">
	<success>True</success>
	<step>finalize</step>
	<usage>
		<stat unit="KB" useOf="MemoryMaximum">1354012.0</stat>
	</usage>
	<input>
		<file GUID="B82104A6-D90E-E211-BFA4-003048F0E7C4" name="PFN:root://eoslhcb.cern.ch//eos/lhcb/grid/prod/lhcb/swtest/lhcb/swtest/R08S14_smallfiles/R08S14EW_small_1_1.dst" status="full">1</file>
		<file GUID="1AA99DA5-D90E-E211-9637-003048F0E7C4" name="PFN:root://eoslhcb.cern.ch//eos/lhcb/grid/prod/lhcb/swtest/lhcb/swtest/R08S14_smallfiles/R08S14EW_small_1_2.dst" status="full">1</file>
		<file GUID="46D8D8A5-D90E-E211-A616-003048F0E7C4" name="PFN:root://eoslhcb.cern.ch//eos/lhcb/grid/prod/lhcb/swtest/lhcb/swtest/R08S14_smallfiles/R08S14EW_small_1_3.dst" status="full">1</file>
		<file GUID="586E9FA5-D90E-E211-91EB-003048F0E7C4" name="PFN:root://eoslhcb.cern.ch//eos/lhcb/grid/prod/lhcb/swtest/lhcb/swtest/R08S14_smallfiles/R08S14EW_small_1_4.dst" status="full">1</file>
		<file GUID="B69019A6-D90E-E211-AC4A-003048F0E7C4" name="PFN:root://eoslhcb.cern.ch//eos/lhcb/grid/prod/lhcb/swtest/lhcb/swtest/R08S14_smallfiles/R08S14EW_small_1_5.dst" status="full">1</file>
	</input>
	<output>
		<file GUID="2013D75F-5FF3-E611-A4E0-1866DA2128C8" name="PFN:merged.dst" status="full">5</file>
	</output>
	<counters>
		<counter name="CounterSummarySvc/handled">21</counter>
	</counters>
	<lumiCounters />
</summary>

=== pseyfertinsecurelogin/LHCb/Kernel/XMLSummaryBase/xml/Summary_Minimal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    (c) Copyright 2018 CERN for the benefit of the LHCb Collaboration

    This software is distributed under the terms of the GNU General Public
    Licence version 3 (GPL Version 3), copied verbatim in the file "COPYING".

    In applying this licence, CERN does not waive the privileges and immunities
    granted to it by virtue of its status as an Intergovernmental Organization
    or submit itself to any jurisdiction.
-->
<summary version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSummary.xsd">
  <success>false</success>
  <step>none</step>
  <usage/>
  <input/>
  <output/>
  <counters/>
  <lumiCounters/>
</summary>

=== pseyfertinsecurelogin/LHCb/Kernel/XMLSummaryBase/tests/qmtest/testtest.xml
<?xml version="1.0" encoding="UTF-8"?>

<summary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:noNamespaceSchemaLocation="XMLSummary.xsd">
  <success>false</success>
  <step>none</step>
  <usage />
  <input>
  	<file GUID="" name="PFN:test/test.dst" status="none">2</file>
  </input>
  <output>
  	<file GUID="" name="PFN:test/testoutput.dst" status="none">2</file>
  </output>
  <counters>
  	<counter name="test/test">2</counter>
  	<statEntity format="Flag Entries Flag2" max="100.0" min="0.0" name="test/testStat">200.0 200.0 200.0</statEntity>
  </counters>
  <lumiCounters />
</summary>
